export const SOCKET_URL = 'ws://127.0.0.1:9090'

export const WEBRTC_SERVER = 'stun:stun.l.google.com:19302'

export const TITLES = {
  GET_ROOMS: 'GET-ROOMS',
  GET_ID: 'GET-ID',
  SET_NAME: 'SET-NAME',
  CREATE_ROOM: 'CREATE-ROOM',
  CLOSE_ROOM: 'CLOSE-ROOM',
  CONNECTION_REQUEST: 'CONNECTION-REQUEST',
  CONNECTION_ANSWER: 'CONNECTION-ANSWER',
  CONNECTION_CLOSED: 'CONNECTION-CLOSED',
}

export const PEER_TITLES = {
  STABILISH_CONNECTION: 'STABILISH-CONNECTION',
  GET_USERS: 'GET-USERS',
}

export const GAME_DIV_ID = '#game'