export const SOCKET_URL = 'ws://127.0.0.1:9090'

export const TITLES = {
  GET_ROOMS: 'GET-ROOMS',
  GET_ID: 'GET-ID',
  SET_NAME: 'SET-NAME',
  CREATE_ROOM: 'CREATE-ROOM',
  CLOSE_ROOM: 'CLOSE-ROOM',
  UPDATE_ROOM: 'UPDATE-ROOM',
  CONNECTION_REQUEST: 'CONNECTION-REQUEST',
  CONNECTION_ANSWER: 'CONNECTION-ANSWER',
  CONNECTION_CLOSED: 'CONNECTION-CLOSED',
}

export const FORCED_CLOSE_TYPES = {
  KICKED: 'kicked',
  BANNED: 'banned',
  FULL: 'full',
  WRONG_PWD: 'WRONG_PWD'
}

export const PEER_TITLES = {
  STABILISH_CONNECTION: 'STABILISH-CONNECTION',
  USER_JOINED: 'USER_JOINED',
  USER_LEFT: 'USER_LEFT',
  GET_USERS: 'GET-USERS',
  SET_ADMIN: 'SET-ADMIN',
  CLOSE: 'CLOSE',
  MESSAGE: 'MESSAGE',
}

export const GAME_DIV_ID = '#game'